a = float(input('Uma distância em metros: '))
print(f'A medida de {a:.1f} corresponde a:')
print(f'{a / 1000}km')
print(f'{a / 100}hm')
print(f'{a / 10}dam')
print(f'{a * 10}dm')
print(f'{a * 100}cm')
print(f'{a * 1000}mm')